name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key to checkout a private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Build and push
        uses: virtualdiner/action-build-typescript@master
        with:
          pushToBranch: true # optional; can either be true or false | defaults to false
          branch: 'dist' # optional; the name of the branch the action should push the compiled code to | defaults to dist
          githubToken: ${{ secrets.GITHUB_TOKEN }} # required if you use the pushToBranch option
          gitIgnoreOverride: 'dist' # Comma seperated overrides to git override files (eg: dist/, build/) etc.
